[phases.setup]
nixPkgs = ["python3", "python3Packages.pip", "ffmpeg"]

[phases.install]
cmds = ["pip install yt-dlp", "npm install"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm start"
